### ISSUE TITLE
Create stub data generator (auto serve stub api with just a spec)

### ISSUE THREAD

**Issue by casualjim** [casualjim/go-swagger#10]
create a data generator that uses an extension property: *x-gen-type*

This property takes a string which is the data generator for that particular type.

for example for a person there might be the following extras:

```yaml
definitions:
  Person:
    properties:
      firstName:
        type: string
        x-gen-type: firstname
      lastName:
        type: string
        x-gen-type: lastname
      age:
        type: string
        x-gen-type: range:10-50
      createdAt:
        type: string
        x-gen-type: date-time:now
```

there are certain generators that will need to take arguments. The syntax above is just a proposal, welcoming suggestions.

The idea is that you can serve a swagger spec to test clients against, and it will know how to generate meaningful data.
So that when you have a backend team implementing a new application, the frontend team can already work with the stubbed out data.  The application should still look kind of acceptable. 
Of course for blurbs of text there is lorem ipsum and so on.

This can be made more useful for testing when it's combined with fuzzer.
